language: python
os: linux
cache:
    pip: true
matrix:
    include:
        - python: "3.9"
          env: NOXSESSION="tests-3.9"
        - python: "3.9"
          env: NOXSESSION="lint"
          dist: xenial
install:
    - pip install nox

script:
    - nox --non-interactive --session "$NOXSESSION"
